# Generated by Django 4.2.7 on 2025-10-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toilets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение')),
                ('coords1', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Координата 1')),
                ('coords2', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Координата 2')),
            ],
            options={
                'verbose_name': 'Туалет',
                'verbose_name_plural': 'Туалеты',
                'db_table': 'toilet',
            },
        ),
    ]
