# Generated by Django 4.2.7 on 2025-10-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilets',
            name='coords1',
            field=models.FloatField(verbose_name='Координата 1'),
        ),
        migrations.AlterField(
            model_name='toilets',
            name='coords2',
            field=models.FloatField(verbose_name='Координата 2'),
        ),
    ]
